// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	//*
	// Get the source of truth/current snapshot of assignments of a shard key
	// to a set of handler addresses
	GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error)
	//*
	// Called by what ever is interested in notifying the controller of
	// updates to membership.
	SaveShard(ctx context.Context, in *SaveShardRequest, opts ...grpc.CallOption) (*SaveShardResponse, error)
	//*
	// Called by admin to delete a shard completely or particular targets for it
	DeleteShard(ctx context.Context, in *DeleteShardRequest, opts ...grpc.CallOption) (*DeleteShardResponse, error)
	//*
	// Returns information about a host as to which shards it (manually) hosts.
	GetTargets(ctx context.Context, in *GetTargetsRequest, opts ...grpc.CallOption) (*GetTargetsResponse, error)
	//*
	// Called to ping a target's health status
	PingTarget(ctx context.Context, in *PingTargetRequest, opts ...grpc.CallOption) (*Target, error)
	//*
	// Called to update a target (most likely its status).
	SaveTarget(ctx context.Context, in *SaveTargetRequest, opts ...grpc.CallOption) (*Target, error)
	//*
	// Deletes/Removes a target - should also remove all associated shards.
	DeleteTargets(ctx context.Context, in *DeleteTargetsRequest, opts ...grpc.CallOption) (*DeleteTargetsResponse, error)
	//*
	// Return all hosts participating in this cluster.
	ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error)
	//*
	// Called by clients interested in being notified about shard assignment updates.
	ConnectClient(ctx context.Context, opts ...grpc.CallOption) (ControlService_ConnectClientClient, error)
	//*
	// Called by shard targets/hosts/producers that host the dataplane for a shard and can be
	// commanded to shard assignment requests.
	ConnectTarget(ctx context.Context, opts ...grpc.CallOption) (ControlService_ConnectTargetClient, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error) {
	out := new(GetShardResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/GetShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SaveShard(ctx context.Context, in *SaveShardRequest, opts ...grpc.CallOption) (*SaveShardResponse, error) {
	out := new(SaveShardResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/SaveShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DeleteShard(ctx context.Context, in *DeleteShardRequest, opts ...grpc.CallOption) (*DeleteShardResponse, error) {
	out := new(DeleteShardResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/DeleteShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetTargets(ctx context.Context, in *GetTargetsRequest, opts ...grpc.CallOption) (*GetTargetsResponse, error) {
	out := new(GetTargetsResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/GetTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) PingTarget(ctx context.Context, in *PingTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	out := new(Target)
	err := c.cc.Invoke(ctx, "/protos.ControlService/PingTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SaveTarget(ctx context.Context, in *SaveTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	out := new(Target)
	err := c.cc.Invoke(ctx, "/protos.ControlService/SaveTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DeleteTargets(ctx context.Context, in *DeleteTargetsRequest, opts ...grpc.CallOption) (*DeleteTargetsResponse, error) {
	out := new(DeleteTargetsResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/DeleteTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error) {
	out := new(ListTargetsResponse)
	err := c.cc.Invoke(ctx, "/protos.ControlService/ListTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ConnectClient(ctx context.Context, opts ...grpc.CallOption) (ControlService_ConnectClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], "/protos.ControlService/ConnectClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceConnectClientClient{stream}
	return x, nil
}

type ControlService_ConnectClientClient interface {
	Send(*ClientControlRequest) error
	Recv() (*ClientControlMessage, error)
	grpc.ClientStream
}

type controlServiceConnectClientClient struct {
	grpc.ClientStream
}

func (x *controlServiceConnectClientClient) Send(m *ClientControlRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controlServiceConnectClientClient) Recv() (*ClientControlMessage, error) {
	m := new(ClientControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) ConnectTarget(ctx context.Context, opts ...grpc.CallOption) (ControlService_ConnectTargetClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[1], "/protos.ControlService/ConnectTarget", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceConnectTargetClient{stream}
	return x, nil
}

type ControlService_ConnectTargetClient interface {
	Send(*TargetControlRequest) error
	Recv() (*TargetControlMessage, error)
	grpc.ClientStream
}

type controlServiceConnectTargetClient struct {
	grpc.ClientStream
}

func (x *controlServiceConnectTargetClient) Send(m *TargetControlRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controlServiceConnectTargetClient) Recv() (*TargetControlMessage, error) {
	m := new(TargetControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility
type ControlServiceServer interface {
	//*
	// Get the source of truth/current snapshot of assignments of a shard key
	// to a set of handler addresses
	GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error)
	//*
	// Called by what ever is interested in notifying the controller of
	// updates to membership.
	SaveShard(context.Context, *SaveShardRequest) (*SaveShardResponse, error)
	//*
	// Called by admin to delete a shard completely or particular targets for it
	DeleteShard(context.Context, *DeleteShardRequest) (*DeleteShardResponse, error)
	//*
	// Returns information about a host as to which shards it (manually) hosts.
	GetTargets(context.Context, *GetTargetsRequest) (*GetTargetsResponse, error)
	//*
	// Called to ping a target's health status
	PingTarget(context.Context, *PingTargetRequest) (*Target, error)
	//*
	// Called to update a target (most likely its status).
	SaveTarget(context.Context, *SaveTargetRequest) (*Target, error)
	//*
	// Deletes/Removes a target - should also remove all associated shards.
	DeleteTargets(context.Context, *DeleteTargetsRequest) (*DeleteTargetsResponse, error)
	//*
	// Return all hosts participating in this cluster.
	ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error)
	//*
	// Called by clients interested in being notified about shard assignment updates.
	ConnectClient(ControlService_ConnectClientServer) error
	//*
	// Called by shard targets/hosts/producers that host the dataplane for a shard and can be
	// commanded to shard assignment requests.
	ConnectTarget(ControlService_ConnectTargetServer) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (UnimplementedControlServiceServer) GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShard not implemented")
}
func (UnimplementedControlServiceServer) SaveShard(context.Context, *SaveShardRequest) (*SaveShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveShard not implemented")
}
func (UnimplementedControlServiceServer) DeleteShard(context.Context, *DeleteShardRequest) (*DeleteShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShard not implemented")
}
func (UnimplementedControlServiceServer) GetTargets(context.Context, *GetTargetsRequest) (*GetTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargets not implemented")
}
func (UnimplementedControlServiceServer) PingTarget(context.Context, *PingTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingTarget not implemented")
}
func (UnimplementedControlServiceServer) SaveTarget(context.Context, *SaveTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTarget not implemented")
}
func (UnimplementedControlServiceServer) DeleteTargets(context.Context, *DeleteTargetsRequest) (*DeleteTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTargets not implemented")
}
func (UnimplementedControlServiceServer) ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTargets not implemented")
}
func (UnimplementedControlServiceServer) ConnectClient(ControlService_ConnectClientServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectClient not implemented")
}
func (UnimplementedControlServiceServer) ConnectTarget(ControlService_ConnectTargetServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectTarget not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_GetShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/GetShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetShard(ctx, req.(*GetShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SaveShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SaveShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/SaveShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SaveShard(ctx, req.(*SaveShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DeleteShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DeleteShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/DeleteShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DeleteShard(ctx, req.(*DeleteShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/GetTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetTargets(ctx, req.(*GetTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_PingTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PingTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/PingTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PingTarget(ctx, req.(*PingTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SaveTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SaveTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/SaveTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SaveTarget(ctx, req.(*SaveTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DeleteTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DeleteTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/DeleteTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DeleteTargets(ctx, req.(*DeleteTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ControlService/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListTargets(ctx, req.(*ListTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ConnectClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).ConnectClient(&controlServiceConnectClientServer{stream})
}

type ControlService_ConnectClientServer interface {
	Send(*ClientControlMessage) error
	Recv() (*ClientControlRequest, error)
	grpc.ServerStream
}

type controlServiceConnectClientServer struct {
	grpc.ServerStream
}

func (x *controlServiceConnectClientServer) Send(m *ClientControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controlServiceConnectClientServer) Recv() (*ClientControlRequest, error) {
	m := new(ClientControlRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ControlService_ConnectTarget_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).ConnectTarget(&controlServiceConnectTargetServer{stream})
}

type ControlService_ConnectTargetServer interface {
	Send(*TargetControlMessage) error
	Recv() (*TargetControlRequest, error)
	grpc.ServerStream
}

type controlServiceConnectTargetServer struct {
	grpc.ServerStream
}

func (x *controlServiceConnectTargetServer) Send(m *TargetControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controlServiceConnectTargetServer) Recv() (*TargetControlRequest, error) {
	m := new(TargetControlRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShard",
			Handler:    _ControlService_GetShard_Handler,
		},
		{
			MethodName: "SaveShard",
			Handler:    _ControlService_SaveShard_Handler,
		},
		{
			MethodName: "DeleteShard",
			Handler:    _ControlService_DeleteShard_Handler,
		},
		{
			MethodName: "GetTargets",
			Handler:    _ControlService_GetTargets_Handler,
		},
		{
			MethodName: "PingTarget",
			Handler:    _ControlService_PingTarget_Handler,
		},
		{
			MethodName: "SaveTarget",
			Handler:    _ControlService_SaveTarget_Handler,
		},
		{
			MethodName: "DeleteTargets",
			Handler:    _ControlService_DeleteTargets_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _ControlService_ListTargets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectClient",
			Handler:       _ControlService_ConnectClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConnectTarget",
			Handler:       _ControlService_ConnectTarget_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/control.proto",
}
